"""initial tables

Revision ID: 6d3a544c8786
Revises: 
Create Date: 2025-11-22 08:42:49.632840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3a544c8786'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('datetime_visited', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('link_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_metrics_id'), 'page_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_page_metrics_url'), 'page_metrics', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_metrics_url'), table_name='page_metrics')
    op.drop_index(op.f('ix_page_metrics_id'), table_name='page_metrics')
    op.drop_table('page_metrics')
    # ### end Alembic commands ###
